import { localCredentials } from './credentials/localCredentials';

export const credentials: Record<string, Record<string, string>> = {
  local: {
    tenantId: localCredentials.tenantId,
    tenantClientId: localCredentials.tenantClientId,
    tenantClientSecret: localCredentials.tenantClientSecret,
    cognitoRegion: localCredentials.cognitoRegion,
    cognitoClientId: localCredentials.cognitoClientId,
    cognitoClientSecret: localCredentials.cognitoClientSecret,
    secJweStr: localCredentials.secJweStr,
    secJwsStr: localCredentials.secJwsStr,
    webJwePrivKey: localCredentials.webJwePrivKey,
    webJwePubKey: localCredentials.webJwePubKey,
    webJwsPrivKey: localCredentials.webJwsPrivKey,
    webJwsPubKey: localCredentials.webJwsPubKey,
    servJwePrivKey: localCredentials.servJwePrivKey,
    servJwePubKey: localCredentials.servJwePubKey,
    servJwsPrivKey: localCredentials.servJwsPrivKey,
    servJwsPubKey: localCredentials.servJwsPubKey,
  },
  dev: {
    tenantId: localCredentials.tenantId,
    tenantClientId: localCredentials.tenantClientId,
    tenantClientSecret: localCredentials.tenantClientSecret,
    cognitoRegion: localCredentials.cognitoRegion,
    cognitoClientId: localCredentials.cognitoClientId,
    cognitoClientSecret: localCredentials.cognitoClientSecret,
    secJweStr: localCredentials.secJweStr,
    secJwsStr: localCredentials.secJwsStr,
    webJwePrivKey: localCredentials.webJwePrivKey,
    webJwePubKey: localCredentials.webJwePubKey,
    webJwsPrivKey: localCredentials.webJwsPrivKey,
    webJwsPubKey: localCredentials.webJwsPubKey,
    servJwePrivKey: localCredentials.servJwePrivKey,
    servJwePubKey: localCredentials.servJwePubKey,
    servJwsPrivKey: localCredentials.servJwsPrivKey,
    servJwsPubKey: localCredentials.servJwsPubKey,
  },
  test: {
    tenantId: localCredentials.tenantId,
    tenantClientId: localCredentials.tenantClientId,
    tenantClientSecret: localCredentials.tenantClientSecret,
    cognitoRegion: localCredentials.cognitoRegion,
    cognitoClientId: localCredentials.cognitoClientId,
    cognitoClientSecret: localCredentials.cognitoClientSecret,
    secJweStr: localCredentials.secJweStr,
    secJwsStr: localCredentials.secJwsStr,
    webJwePrivKey: localCredentials.webJwePrivKey,
    webJwePubKey: localCredentials.webJwePubKey,
    webJwsPrivKey: localCredentials.webJwsPrivKey,
    webJwsPubKey: localCredentials.webJwsPubKey,
    servJwePrivKey: localCredentials.servJwePrivKey,
    servJwePubKey: localCredentials.servJwePubKey,
    servJwsPrivKey: localCredentials.servJwsPrivKey,
    servJwsPubKey: localCredentials.servJwsPubKey,
  },
  uat: {
    tenantId: localCredentials.tenantId,
    tenantClientId: localCredentials.tenantClientId,
    tenantClientSecret: localCredentials.tenantClientSecret,
    cognitoRegion: localCredentials.cognitoRegion,
    cognitoClientId: localCredentials.cognitoClientId,
    cognitoClientSecret: localCredentials.cognitoClientSecret,
    secJweStr: localCredentials.secJweStr,
    secJwsStr: localCredentials.secJwsStr,
    webJwePrivKey: localCredentials.webJwePrivKey,
    webJwePubKey: localCredentials.webJwePubKey,
    webJwsPrivKey: localCredentials.webJwsPrivKey,
    webJwsPubKey: localCredentials.webJwsPubKey,
    servJwePrivKey: localCredentials.servJwePrivKey,
    servJwePubKey: localCredentials.servJwePubKey,
    servJwsPrivKey: localCredentials.servJwsPrivKey,
    servJwsPubKey: localCredentials.servJwsPubKey,
  },
  prod: {
    tenantId: localCredentials.tenantId,
    tenantClientId: localCredentials.tenantClientId,
    tenantClientSecret: localCredentials.tenantClientSecret,
    cognitoRegion: localCredentials.cognitoRegion,
    cognitoClientId: localCredentials.cognitoClientId,
    cognitoClientSecret: localCredentials.cognitoClientSecret,
    secJweStr: localCredentials.secJweStr,
    secJwsStr: localCredentials.secJwsStr,
    webJwePrivKey: localCredentials.webJwePrivKey,
    webJwePubKey: localCredentials.webJwePubKey,
    webJwsPrivKey: localCredentials.webJwsPrivKey,
    webJwsPubKey: localCredentials.webJwsPubKey,
    servJwePrivKey: localCredentials.servJwePrivKey,
    servJwePubKey: localCredentials.servJwePubKey,
    servJwsPrivKey: localCredentials.servJwsPrivKey,
    servJwsPubKey: localCredentials.servJwsPubKey,
  },
};
