import type { Metadata } from 'next';
//Internal app
import './globals.css';
import { RootLayout } from '@/interfaces';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayoutMain({ children, params }: RootLayout) {
  return (
    <html lang={params?.lang}>
      <body>
        <div className="bg-white min-h-screen w-full color-text">{children}</div>
      </body>
    </html>
  );
}
